### ISSUE TITLE
Official mongodb driver

### ISSUE THREAD

**Issue by Pepeye** [mehmetsefabalik/rust-mongodb-example#2]
Hi @mehmetsefabalik 

Discovered this repo by chance on Reddit. Been looking for examples of actix, mongodb (official driver) and connection pooling. Good job.

As `r2d2-mongodb` is now deprecated as stated [here](https://gitlab.com/petoknm/r2d2-mongodb/-/issues/6) - `r2d2 is not needed for mongodb driver since it maintains its own connection pool. I will be deprecating this crate.`

Are you planning on updating this to use the official mongodb crate (0.9+) and without r2d2?

**Comment by mehmetsefabalik** [comment]
Hi @Pepeye I am using official mongodb crate (0.9+) in my real world projects, This repo needs to be updated as you said, I will make the necessary updates and notify you 👍 thank you for your concern

**Comment by mehmetsefabalik** [comment]
@Pepeye I updated mongodb adapter, you can check the commit to see the diff: 471efa5ac36576e2928d1967738b2d17203fad57

**Comment by Pepeye** [comment]
Noted @mehmetsefabalik Thanks.
